#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	echo Running: ../../.github/citools/ruby/ruby-lint-rubycritic
	time ../../.github/citools/ruby/ruby-lint-rubycritic

	print_ruler

	echo Running: ../../.github/citools/ruby/ruby-test-with-coverage
	time ../../.github/citools/ruby/ruby-test-with-coverage

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest
	# still looking for a working version for ruby

	echo Running: misspell .
	time misspell .

	print_ruler

	cd ..
	pwd

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-ruby.txt
