#!/bin/bash

declare pkg_name
declare d

time for d in ./*; do
	[[ -d ${d} ]] || continue
	cd "${d}" || continue
	printf "[dir: %s]\n\n" "${PWD}"

	pkg_name="$(basename "${PWD}")"

	printf "[pkg: %s]\n\n" "${pkg_name}"

	echo "${@}"
	time "${@}"

	printf "\n"

	cd - || break
done
