#!/bin/bash

print_ruler()
{
	printf "\n"
	printf "=%.0s" {1..79}; printf "\n"
	printf "\n"
} # print_ruler()

main()
{
	printf "Running automated test file(s):\n\n"

	print_ruler

	# https://github.com/dart-lang/linter

	echo dart analyze .
	time dart analyze .

	print_ruler

	# https://github.com/dart-lang/test

	echo dart test .
	time dart test .

	print_ruler

	# https://github.com/dart-lang/coverage
	# dart pub global activate coverage

	echo dart pub global run coverage:test_with_coverage
	time dart pub global run coverage:test_with_coverage

	print_ruler

	# https://github.com/linux-test-project/lcov

	echo lcov --summary ./coverage/lcov.info
	time lcov --summary ./coverage/lcov.info

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest

	echo misspell .
	time misspell .

	print_ruler

	# https://github.com/dart-lang/pana
	# dart pub global activate pana

	echo dart pub global run pana .
	time dart pub global run pana .

	print_ruler

	# https://github.com/dart-lang/dartdoc

	echo dart doc .
	time dart doc .

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-dart.txt
