#!/bin/bash

declare -i retval=0

export BATS_RUN_SKIPPED=true

for tf in ./*.bats; do
	echo Running: bats "${tf}"
	time bats "${tf}" || ((retval++))
	printf "\n"
done

echo exit "${retval}"
exit "${retval}"
