#!/bin/bash

declare -i retval=0

# git clone http://git.savannah.gnu.org/r/gawk.git
# cd gawk
# git checkout $(awk --version | awk '/^GNU Awk/ { print $3 }' | tr -d ',')
# cd ..
# git clone https://github.com/soimort/awkunit
# cd awkunit
# AWKSRCPATH=../gawk make
# cp -v awkunit.so ~/.local/gawk/lib/awkunit.so

# awkunit.so file needs to be in the lib directory
# awkunit.awk file needs to be in the current directory

AWKLIBPATH="$(gawk 'BEGIN {print ENVIRON["AWKLIBPATH"]}'):../.lib"
export AWKLIBPATH

printf "AWKLIBPATH=%s\n\n" "${AWKLIBPATH}"
for d in ${AWKLIBPATH//:/ }; do
	printf "%s\n" "${d}"
	ls "${d}"
	printf "\n"
done

declare lint_default_vars
if [[ -f .lint_default_vars ]]; then
	read -r lint_default_vars <.lint_default_vars
fi

# shellcheck disable=SC2028
echo Running: gawk "${lint_default_vars}" --file ./*_test.awk "&&" printf "\n%s\n" "Tests Passed!" "||" printf "\n%s\n" "Tests Failed!"
# shellcheck disable=SC2086
if time gawk ${lint_default_vars} --file ./*_test.awk; then
	printf "\n%s\n" "Tests Passed!"
else
	((retval++))
	printf "\n%s\n" "Tests Failed!"
fi
printf "\n"

echo exit "${retval}"
exit "${retval}"
