#!/bin/bash

declare -i retval=0

AWKLIBPATH="$(gawk 'BEGIN {print ENVIRON["AWKLIBPATH"]}'):../.lib"
export AWKLIBPATH

printf "AWKLIBPATH=%s\n\n" "${AWKLIBPATH}"
for d in ${AWKLIBPATH//:/ }; do
	printf "%s\n" "${d}"
	ls "${d}"
	printf "\n"
done

for tf in ./*.awk; do
	if [[ ${tf} =~ _test.awk ]]; then
		continue
	fi

	echo gawk --lint --file="${tf}" "<" /dev/null ">" /dev/null
	time gawk --lint --file="${tf}" </dev/null >/dev/null || ((retval++))
	printf "\n"
done

echo exit "${retval}"
exit "${retval}"
