#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	echo Running: make clean
	time make clean

	print_ruler

	# https://www.throwtheswitch.org/unity

	echo Running: make test '|' ansifilter
	time make test | ansifilter

	print_ruler

	# https://www.throwtheswitch.org/unity

	echo Running: make memcheck '|' ansifilter
	time make memcheck | ansifilter

	print_ruler

	# https://clang.llvm.org/docs/ClangFormat.html

	echo Running: clang-format-16 -style=file -i ./*.c ./*.h
	time clang-format-16 -style=file -i ./*.c ./*.h

	print_ruler

	# https://clang.llvm.org/docs/ClangCheck.html

	echo Running: ../../.github/citools/cpp/clang-check
	time ../../.github/citools/cpp/clang-check

	print_ruler

	# https://clang.llvm.org/extra/clang-tidy/

	echo Running: ../../.github/citools/cpp/clang-tidy '|' head -n 100
	time ../../.github/citools/cpp/clang-tidy | head -n 100

	print_ruler

} # main()

time main "$@" |& tee ./run-tests-c.txt
