#!/bin/bash

if [[ ! -d .exercism ]]; then
	printf "ERROR: Run from inside a project directory.\n\n"
	exit 1
fi

# declare package_name_snake

get_awk_package_name() {
	# these are kebab-case
	basename "${PWD}"
} # get_awk_package_name()

kebab_case_to_pascal_case() {
	printf "%s" "${@}" | sed -r -e 's/(^|[-])(\w)/\U\2/g'
} # kebab_case_to_pascal_case()

kebab_case_to_camel_case() {
	printf "%s" "${@}" | sed -r -e 's/([-])(\w)/\U\2/g'
} # kebab_case_to_camel_case()

kebab_case_to_snake_case() {
	printf "%s" "${@}" | sed -r -e 's/(\w)([-])(\w)/\1_\3/g'
} # kebab_case_to_snake_case()

# package_name_snake="$(kebab_case_to_snake_case "$(get_awk_package_name)")"

declare -a C_FILES

mapfile -t C_FILES < <(
	find . -maxdepth 1 -type f -name "*[.][c]" | grep -v -E "test_.*[.]c"
	find . -maxdepth 1 -type f -name "*[.][h]" | grep -v -E "test_.*[.]c"
)

echo Running: exercism submit "${C_FILES[@]}" run-tests-c.txt
time exercism submit "${C_FILES[@]}" run-tests-c.txt
printf "\n"
