#!/bin/bash

if [[ ! -d .exercism ]]; then
	printf "ERROR: Run from inside a project directory.\n\n"
	exit 1
fi

# declare package_name_snake

get_awk_package_name() {
	# these are kebab-case
	basename "${PWD}"
} # get_awk_package_name()

kebab_case_to_pascal_case() {
	printf "%s" "${@}" | sed -r -e 's/(^|[-])(\w)/\U\2/g'
} # kebab_case_to_pascal_case()

kebab_case_to_camel_case() {
	printf "%s" "${@}" | sed -r -e 's/([-])(\w)/\U\2/g'
} # kebab_case_to_camel_case()

kebab_case_to_snake_case() {
	printf "%s" "${@}" | sed -r -e 's/(\w)([-])(\w)/\1_\3/g'
} # kebab_case_to_snake_case()

# package_name_snake="$(kebab_case_to_snake_case "$(get_awk_package_name)")"

if ls ./*.hpp >&/dev/null; then
	printf "The header files have been converted to CPP, can't submit.\n"
	printf "\n"
	ls ./*.cpp ./*.hpp
	printf "\n"
	exit 1
fi

declare -a CPP_FILES

mapfile -t CPP_FILES < <(
	find . -maxdepth 1 -type f -name "*[.]cpp" | grep -v "_test[.]cpp"
	#find . -maxdepth 1 -type f -name "*[.]hpp" | grep -v "_test[.]cpp"
	find . -maxdepth 1 -type f -name "*[.]h" | grep -v "_test[.]cpp"
)

echo Running: exercism submit "${CPP_FILES[@]}" run-tests-cpp.txt
time exercism submit "${CPP_FILES[@]}" run-tests-cpp.txt
printf "\n"
