#!/bin/bash

if [[ ! -d .exercism ]]; then
	printf "ERROR: Run from inside a project directory.\n\n"
	exit 1
fi

declare package_name
declare project_dir

package_name="$(basename "${PWD}")"
project_dir="$(basename "${PWD}")"

if ! grep -q ./"${project_dir}"/README.md ../README.md; then

cat >> ../README.md <<EOF
- [${project_dir}](./${project_dir}/README.md)
EOF

fi

if ! grep -q ./"${package_name}"-doc.md ./README.md; then

	# Two empty spaces because the file is missing a trailing new line.
cat >> ./README.md <<EOF


### My Solution

- [my solution]($(printf "%s\n" ./*[.]vim | grep -v -E "[.](vader|vimspec)"))
EOF

cat >> ./README.md <<EOF
- [vader tests]($(printf "%s\n" ./*[.]vader))
EOF

cat >> ./README.md <<EOF
- [themis tests](./themis.vimspec)
EOF

cat >> ./README.md <<EOF
- [themis profile](./profile.txt)
EOF

cat >> ./README.md <<EOF
- [run-tests output](./run-tests-vimscript.txt)
EOF

fi

printf "\n"
git add ../README.md ./README.md
git diff --cached ../README.md ./README.md
