#!/bin/bash
#
# .github/citools/includes/wrapper-library
#

set -o pipefail

md_code_tag() {
	if [[ -n ${GITHUB_STEP_SUMMARY} ]]; then
		printf "\`\`\`%s\n" "${1}"

		if [[ -z ${1} ]]; then
			printf "\n"
		fi
	fi
} # md_code_tag()

run_command() {
	# md_code_tag text
	echo Running: "${@}"
	printf "\n"
	# shellcheck disable=SC2154
	time "${@}" || ((retval--))
	printf "\n"
	# md_code_tag
} # run_command()

track_errors() {
	((retval++))
	printf "\nERROR: Failure detected in last command.\n"
} # track_errors()

print_ruler() {
	printf "\n "
	printf "=%.0s" {1..78}
	printf "\n"
	printf "\n"
} # print_ruler()

get_rust_package_name() {
	toml get Cargo.toml package | jq -r .name
} # get_rust_package_name()

show_tool_versions_rust_short() {
	# md_code_tag text
	printf "Rust versions:\n"
	printf "\n"
	rustc --version | paste /dev/null -
	rustup --version | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_rust_short()

show_tool_versions_rust() {
	show_tool_versions_rust_short

	if [[ -z ${GITHUB_ACTIONS} ]]; then
		return
	fi

	# md_code_tag text
	printf "Installed cargo crates:\n"
	printf "\n"
	cargo install --list | paste /dev/null -
	# md_code_tag
	printf "\n"

	# md_code_tag text
	rustup --version
	# md_code_tag
	printf "\n"

	# md_code_tag text
	printf "Installed rustup components:\n"
	printf "\n"
	rustup component list | grep '(installed)' | paste /dev/null -
	# md_code_tag
	printf "\n"

	# md_code_tag text
	printf "Environment variables:\n"
	printf "\n"
	printf "%s=%s\n" "PATH" "${PATH}"
	printf "\n"
	printf "%s=%s\n" "CARGO_REGISTRIES_CRATES_IO_PROTOCOL" "${CARGO_REGISTRIES_CRATES_IO_PROTOCOL}" "RUSTC_WRAPPER" "${RUSTC_WRAPPER}"
	# md_code_tag
	printf "\n"
} # show_tool_versions_rust()

show_tool_versions_go_short() {
	# md_code_tag text
	printf "Go version:\n"
	printf "\n"
	go version | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_go_short()

show_tool_versions_go() {
	show_tool_versions_go_short

	if [[ -z ${GITHUB_ACTIONS} ]]; then
		return
	fi

	# md_code_tag text
	printf "Installed Go packages:\n"
	printf "\n"
	# shellcheck disable=SC2012
	ls "${HOME}"/go/bin | paste /dev/null -
	# md_code_tag
	printf "\n"

	# md_code_tag text
	printf "Environment variables:\n"
	printf "\n"
	printf "%s=%s\n" "PATH" "${PATH}"
	printf "\n"
	printf "%s=%s\n" "GOBIN" "${GOBIN}" "GOPATH" "${GOPATH}"
	# md_code_tag
	printf "\n"
} # show_tool_versions_go()

show_tool_versions_ruby_short() {
	# md_code_tag text
	printf "Ruby versions:\n"
	printf "\n"
	ruby --version | paste /dev/null -
	rbenv --version | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_ruby_short()

show_tool_versions_ruby() {
	show_tool_versions_ruby_short

	if [[ -z ${GITHUB_ACTIONS} ]]; then
		return
	fi

	# md_code_tag text
	printf "Installed Gem packages:\n"
	printf "\n"
	gem list | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_ruby()

show_tool_versions_node_short() {
	# md_code_tag text
	printf "Node versions:\n"
	printf "\n"
	{
		printf "nodejs: "
		nodejs --version
	} | paste /dev/null -
	{
		printf "   npm: "
		npm --version
	} | paste /dev/null -
	{
		printf "  yarn: "
		yarn --version
	} | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_node_short()

show_tool_versions_node() {
	show_tool_versions_node_short

	if [[ -z ${GITHUB_ACTIONS} ]]; then
		return
	fi

	# md_code_tag text
	printf "Installed npm packages:\n"
	printf "\n"
	npm list --global | paste /dev/null -
	# md_code_tag
	printf "\n"

	# md_code_tag text
	printf "Installed yarn packages:\n"
	printf "\n"
	yarn global list | paste /dev/null -
	# md_code_tag
	printf "\n"
} # show_tool_versions_node()
