#!/bin/bash

shopt -s nullglob

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

echo Running: clang-check-"${LLVM_VER}" --analyze "${@}" ./*.cpp ./*.hpp ./*.h
time clang-check-"${LLVM_VER}" --analyze "${@}" ./*.cpp ./*.hpp ./*.h
printf "\n"
