#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	echo Running: ../../.github/citools/wasm/wasm-lint-formatter
	time ../../.github/citools/wasm/wasm-lint-formatter

	print_ruler

	echo Running: npm install
	time npm install

	print_ruler

	echo Running: ../../.github/citools/wasm/wasm-test-with-coverage
	time ../../.github/citools/wasm/wasm-test-with-coverage

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest
	# still looking for a working version for wasm

	echo Running: misspell ./*.wat
	time misspell ./*.wat

	print_ruler

	cd ..
	pwd

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-wasm.txt
