#!/bin/sh
#
# .github/docker/include
#
# Usage: source from layer script and call the functions
#
# Notes:
# - use sh/posix syntax only

layer_begin() {
	printf "=== %s:%s start ===\n\n" "${0}" "layer_begin()"

	printf "%s: %s\n" "$1" "$(date +%Y%m%d-%H%M%S)" >/etc/ci-image-info
	cat /etc/ci-image-info
	printf "\n"

	echo apt update
	apt update || exit
	printf "\n"

	echo apt list --upgradable
	apt list --upgradable || exit
	printf "\n"

	echo apt upgrade -y
	apt upgrade -y || exit
	printf "\n"

	printf "=== %s:%s end ===\n\n" "${0}" "layer_begin()"
}

layer_end() {
	printf "=== %s:%s start ===\n\n" "${0}" "layer_end()"

	echo apt-get clean
	apt-get clean || exit
	printf "\n"

	echo rm -rf /var/lib/apt/lists/*
	rm -rf /var/lib/apt/lists/* || exit
	printf "\n"

	printf "=== %s:%s end ===\n\n" "${0}" "layer_end()"
}
