#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-check.html

	echo Running: cargo check --release
	time cargo check --release

	print_ruler

	# https://github.com/rust-lang/rust-clippy

	echo Running: cargo clippy --release
	time cargo clippy --release

	print_ruler

	# https://github.com/RustSec/rustsec/tree/main/cargo-audit

	echo Running: cargo audit
	time cargo audit

	print_ruler

	echo rm -fv ./*.profraw ./*.profdata
	rm -fv ./*.profraw ./*.profdata

	print_ruler

	echo Running: ../../.github/citools/rust/rust-test-with-tarpaulin
	time ../../.github/citools/rust/rust-test-with-tarpaulin

	print_ruler

	echo Running: ../../.github/citools/rust/rust-test-with-llvm-coverage
	time ../../.github/citools/rust/rust-test-with-llvm-coverage
	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest
	# still looking for a working version for rust

	echo Running: misspell .
	time misspell .

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-doc.html

	echo Running: cargo doc
	time cargo doc

	print_ruler

	echo Running: cargo clean
	time cargo clean

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-rust.txt
