#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-check.html

	echo Running: ../../.github/citools/rust/rust-lint-check --release
	time ../../.github/citools/rust/rust-lint-check --release

	print_ruler

	# https://github.com/rust-lang/rust-clippy

	echo Running: ../../.github/citools/rust/rust-lint-clippy --release
	time ../../.github/citools/rust/rust-lint-clippy --release

	print_ruler

	# https://github.com/RustSec/rustsec/tree/main/cargo-audit

	echo Running: ../../.github/citools/rust/rust-lint-audit
	time ../../.github/citools/rust/rust-lint-audit

	print_ruler

	echo rm -fv ./*.profraw ./*.profdata
	rm -fv ./*.profraw ./*.profdata

	print_ruler

	echo Running: ../../.github/citools/rust/rust-test-with-tarpaulin
	time ../../.github/citools/rust/rust-test-with-tarpaulin

	print_ruler

	echo Running: ../../.github/citools/rust/rust-test-with-llvm-coverage
	time ../../.github/citools/rust/rust-test-with-llvm-coverage

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest
	# still looking for a working version for rust

	echo Running: misspell .
	time misspell .

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-doc.html

	echo Running: cargo doc
	time cargo doc

	print_ruler

	echo Running: cargo clean
	time cargo clean

	print_ruler

	cd ..
	pwd

	print_ruler

	{
		printf "[workspace]\n"
		printf "resolver = \"%d\"\n" 2
		printf "members = [\n"
		for d in ./*; do
			if [[ -d $d ]]; then
				printf "    \"%s\",\n" "$d"
			fi
		done
		printf "]\n"
	} >Cargo.toml

	print_ruler

	echo Running: rust-analyzer -v lsif . '>' index.lsif
	time rust-analyzer -v lsif . >index.lsif

	print_ruler

	echo Running: rust-analyzer -v scip .
	time rust-analyzer -v scip .

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-rust.txt
