#!/bin/bash

if [[ ! -d .exercism ]]; then
	printf "ERROR: Run from inside a project directory.\n\n"
	exit 1
fi

# declare package_name_snake

get_awk_package_name() {
	# these are kebab-case
	basename "${PWD}"
} # get_awk_package_name()

kebab_case_to_pascal_case() {
	printf "%s" "${@}" | sed -r -e 's/(^|[-])(\w)/\U\2/g'
} # kebab_case_to_pascal_case()

kebab_case_to_camel_case() {
	printf "%s" "${@}" | sed -r -e 's/([-])(\w)/\U\2/g'
} # kebab_case_to_camel_case()

kebab_case_to_snake_case() {
	printf "%s" "${@}" | sed -r -e 's/(\w)([-])(\w)/\1_\3/g'
} # kebab_case_to_snake_case()

# package_name_snake="$(kebab_case_to_snake_case "$(get_awk_package_name)")"

declare -a GO_FILES

mapfile -t GO_FILES < <(
	find . -type f -name "*[.]go" | grep -v "_test[.]go"
	find . -type f -name "*_examples_test[.]go"
)

echo Running: exercism submit "${GO_FILES[@]}" ./benchstat-*.txt run-tests-go.txt
time exercism submit "${GO_FILES[@]}" ./benchstat-*.txt run-tests-go.txt
printf "\n"
