#!/bin/bash
#
# .github/citools/ruby/ruby-setup-config
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "Setup Ruby Environment\n\n"

	print_ruler

	source ../../.github/citools/common/gh-setup-env || exit

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
