#!/bin/bash
#
# .github/citools/ruby/ruby-setup-install
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "Ruby Installation\n\n"

	print_ruler

	echo Running: sudo apt update
	time sudo apt update || track_errors

	print_ruler

	local -a debs
	debs=(
		autoconf
		automake
		bison
		bc
		build-essential
		curl
		g++
		gcc
		git
		gnupg
		libc6-dev
		libffi-dev
		libgdbm-dev
		libgmp-dev
		libncurses5-dev
		libreadline-dev
		libsqlite3-dev
		libssl-dev
		libtool
		libyaml-dev
		make
		pkg-config
		sqlite3
		zlib1g-dev
	)

	echo Running: sudo apt install -y "${debs[@]}"
	time sudo apt install -y "${debs[@]}" || track_errors

	print_ruler

	echo Running: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer \| bash
	time curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash || track_errors

	print_ruler

	printf "Configuring Shell: "
	# shellcheck disable=SC2016
	{
		echo 'export PATH="${HOME}/.rbenv/bin:${HOME}/.rbenv/bin/shims:${PATH}"' >>"${HOME}"/.profile
		echo 'eval "$(rbenv init -)"' >>"${HOME}"/.profile
	}
	# shellcheck disable=SC1090
	source "${HOME}"/.profile || track_errors
	printf "done\n"

	print_ruler

	echo Running: rbenv -v
	time rbenv -v || track_errors

	print_ruler

	echo Running: rbenv install --list
	time rbenv install --list || track_errors

	print_ruler

	local ruby_version
	ruby_version="$(rbenv install --list 2>/dev/null | grep '^3[.][0-9][.]' | tail -n 1)" || track_errors

	echo Running: rbenv install "${ruby_version}"
	time rbenv install "${ruby_version}" || track_errors

	print_ruler

	echo Running: rbenv global "${ruby_version}"
	time rbenv global "${ruby_version}" || track_errors

	print_ruler

	echo Running: ruby -v
	time ruby -v || track_errors

	print_ruler

	local -a gems
	gems=(
		rspec
		rspec-core
		rspec-expectations
		rspec-mocks
		rspec-parameterized
		rspec-support
		rubycritic
		simplecov
		simplecov-cobertura
	)

	echo Running: gem install "${gems[@]}"
	time gem install "${gems[@]}" || track_errors

	print_ruler

	echo Running: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-doctor \| bash
	time curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-doctor | bash || track_errors

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
