#!/bin/bash

declare -i retval=0
declare pkg_name
declare d

time for d in ./*; do
	[[ -d ${d} ]] || continue
	cd "${d}" || continue
	printf "[dir: %s]\n\n" "${PWD}"

	pkg_name="$(basename "${PWD}")"

	printf "[pkg: %s]\n\n" "${pkg_name}"

	echo "${@}"
	if ! time "${@}"; then
		((retval++))
		printf "\n"
		printf "Exit Code: %s\n" "FAILED"
	else
		printf "\n"
		printf "Exit Code: %s\n" "SUCCESS"
	fi

	printf "\n"

	cd - || break
done
printf "\n"

printf "Error Count: %d\n" "${retval}"
exit "${retval}"
