#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	export PYTHONPATH="."

	printf "Running automated test file(s):\n\n"

	print_ruler

	# https://github.com/pylint-dev/pylint

	echo Running: ../../.github/citools/python/python-lint-pylint
	time ../../.github/citools/python/python-lint-pylint

	print_ruler

	# https://github.com/charliermarsh/ruff

	echo Running: ../../.github/citools/python/python-lint-ruff
	time ../../.github/citools/python/python-lint-ruff

	print_ruler

	# https://github.com/microsoft/pyright

	echo Running: ../../.github/citools/python/python-lint-pyright
	time ../../.github/citools/python/python-lint-pyright

	print_ruler

	# https://github.com/PyCQA/bandit

	echo Running: ../../.github/citools/python/python-lint-bandit
	time ../../.github/citools/python/python-lint-bandit

	print_ruler

	# https://github.com/dosisod/refurb

	echo Running: ../../.github/citools/python/python-lint-refurb
	time ../../.github/citools/python/python-lint-refurb

	print_ruler

	echo Running: ../../.github/citools/python/python-test-with-doctests
	time ../../.github/citools/python/python-test-with-doctests

	print_ruler

	# https://github.com/pytest-dev/pytest

	echo Running: ../../.github/citools/python/python-test-with-coverage
	time ../../.github/citools/python/python-test-with-coverage

	print_ruler

	echo tail -n 10000 './*,cover' '|' grep -E -C 3 "'^> def |^! '"
	tail -n 10000 ./*,cover | grep -E -C 1 '^> def |^! '

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest

	echo Running: misspell ./src/*/*py
	time misspell ./src/*/*py

	print_ruler

} # main()

time main "$@" |& tee ./run-tests-python.txt
