#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	export PYTHONPATH="."

	printf "Running automated test file(s):\n\n"

	print_ruler

	# https://github.com/pylint-dev/pylint

	echo Running: pylint ./src
	time pylint ./src

	print_ruler

	# https://github.com/charliermarsh/ruff

	echo Running: ruff check --ignore E501 ./src
	time ruff check --ignore E501 ./src

	print_ruler

	# https://github.com/microsoft/pyright

	echo Running: pyright --stats ./src
	time pyright --stats ./src

	print_ruler

	# https://github.com/PyCQA/bandit

	echo Running: bandit --verbose --recursive ./src
	time bandit --verbose --recursive ./src

	print_ruler

	# https://github.com/dosisod/refurb

	echo Running: refurb ./src
	time refurb ./src

	print_ruler

	echo python -m doctest -v ./src/*/*py
	time python -m doctest -v ./src/*/*py
	printf "\n"

	print_ruler

	# https://github.com/pytest-dev/pytest

	tail -v -n 1000 .coveragerc
	printf "\n"

	echo Running: PYTHONPATH="./src" pytest --verbose --cov=. --cov-branch --cov-report={term-missing,xml:.coverage.xml} -p no:randomly ./test
	time { PYTHONPATH="./src" pytest --verbose --cov=. --cov-branch --cov-report={term-missing,xml:.coverage.xml} -p no:randomly ./test; }

	print_ruler

	echo Running: coverage report --show-missing
	time coverage report --show-missing

	print_ruler

	echo coverage annotate
	time coverage annotate
	printf "\n"

	echo tail -n 10000 './*,cover' '|' grep -E -C 3 "'^> def |^! '"
	tail -n 10000 ./*,cover | grep -E -C 1 '^> def |^! '

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest

	echo Running: misspell ./src/*/*py
	time misspell ./src/*/*py

	print_ruler

} # main()

time main "$@" |& tee ./run-tests-python.txt
