#!/bin/bash
#
# .github/citools/wasm/wasm-lint-formatter
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning WebAssembly Formatter\n\n"

	show_tool_versions_node_short

	print_ruler

	# https://github.com/beautify-web/js-beautify
	# https://github.com/prettier/eslint-config-prettier

	run_command js-beautify ./*.js

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
