#!/bin/bash
#
# .github/citools/wasm/wasm-setup-verify
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -A wasm_cmds

wasm_cmds=(
	[node]=$(
		command -v node >&/dev/null
		echo "$?"
	)
	[npm]=$(
		command -v npm >&/dev/null
		echo "$?"
	)
	[yarn]=$(
		command -v yarn >&/dev/null
		echo "$?"
	)
)

main() {
	printf "Verifying WebAssembly Installation\n\n"

	print_ruler

	printf "RBENV_SHELL=%s\n" "${RBENV_SHELL}"
	printf "PATH=%s\n" "${PATH}"

	print_ruler

	for key in "${!wasm_cmds[@]}"; do
		if [[ ${wasm_cmds[${key}]} -ne 0 ]]; then
			printf "ERROR: command [%s] not found.\n" "${key}"
			((retval++))
		fi
	done

	if [[ ${retval} -ne 0 ]]; then
		return "${retval}"
	fi

	print_ruler

	show_tool_versions_node

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
