#!/bin/bash
#
# .github/citools/wasm/wasm-setup-install
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "WebAssembly Installation\n\n"

	print_ruler

	echo Running: sudo apt update
	time sudo apt update || track_errors

	print_ruler

	local -a debs
	debs=(
		nodejs
		npm
		yarn
	)

	echo Running: sudo apt install -y "${debs[@]}"
	time sudo apt install -y "${debs[@]}" || track_errors

	print_ruler

	show_tool_versions_node_short

	print_ruler

	local -a npm_pkgs
	npm_pkgs=(
		eslint
		eslint-config-prettier
		js-beautify
		prettier
	)

	echo Running: npm install --global "${npm_pkgs[@]}"
	time npm install --global "${npm_pkgs[@]}" || track_errors

	print_ruler

	show_tool_versions_node_short

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
