#!/bin/bash
#
# .github/citools/wasm/wasm-test-with-coverage
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning WebAssembly Tests With Coverage\n\n"

	show_tool_versions_node_short

	print_ruler

	run_command rm -rf ./coverage

	print_ruler

	run_command npm run test -- --coverage || ((retval++))

	print_ruler

	run_command lcov --list ./coverage/lcov.info

	print_ruler

	run_command lcov --summary ./coverage/lcov.info

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
