name: 'hello_world'
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: '<2.0.0'
homepage: 'https://exercism.org/tracks/dart/exercises/hello-world'
repository: 'https://github.com/vpayno/exercism-workspace/tree/main/dart/hello-world'
