#!/bin/bash
#
# .github/citools/python/python-lint-bandit
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Python Lint - Bandit\n\n"

	show_tool_versions_python_short

	print_ruler

	run_command bandit --version

	print_ruler

	# shellcheck disable=SC2048,SC2068,SC2086
	run_command bandit ${@:---verbose --recursive ./src}

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
