#!/bin/bash
#
# .github/citools/python/python-lint-pylint
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Python Lint - PyLint\n\n"

	show_tool_versions_python_short

	print_ruler

	run_command pylint --version

	print_ruler

	# shellcheck disable=SC2048,SC2068,SC2086
	run_command pylint ${@:-./src}

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
