#!/bin/bash
#
# .github/citools/python/python-test-doctest
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Python DocTests\n\n"

	show_tool_versions_python_short

	print_ruler

	export PYTHONPATH="./src"
	printf "PYTHONPATH=\"%s\"\n" "${PYTHONPATH}"

	print_ruler

	# shellcheck disable=SC2048,SC2068,SC2086
	run_command python -m doctest ${@:--v ./src/*/*.py}

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
