#!/bin/bash
#
# .github/citools/r/r-setup-verify
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -A r_cmds

r_cmds=(
	[R]=$(
		command -v R >&/dev/null
		echo "$?"
	)
	[Rscript]=$(
		command -v Rscript >&/dev/null
		echo "$?"
	)
)

main() {
	printf "Verifying R Installation\n\n"

	print_ruler

	printf "PATH=%s\n" "${PATH}"

	print_ruler

	for key in "${!r_cmds[@]}"; do
		if [[ ${r_cmds[${key}]} -ne 0 ]]; then
			printf "ERROR: command [%s] not found.\n" "${key}"
			((retval++))
		fi
	done

	if [[ ${retval} -ne 0 ]]; then
		return "${retval}"
	fi

	print_ruler

	show_tool_versions_r

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
