#!/bin/bash

CLANG_TIDY_CHECKS="*,-llvm-header-guard,-llvmlibc-restrict-system-libc-headers"

echo Running: clang-tidy-16 ./*.c ./*.h -checks="${CLANG_TIDY_CHECKS}" --
time clang-tidy-16 ./*.c ./*.h -checks="${CLANG_TIDY_CHECKS}" --
printf "\n"
