#!/bin/bash

shopt -s nullglob

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

echo Running: clang-tidy-"${LLVM_VER}" "${@}" ./*.c ./*.h
time clang-tidy-"${LLVM_VER}" "${@}" ./*.c ./*.h
printf "\n"
