#!/bin/bash

shopt -s nullglob

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

echo clang-check-"${LLVM_VER}" --analyze "${@}" ./*.c ./*.h
time clang-check-"${LLVM_VER}" --analyze "${@}" ./*.c ./*.h
printf "\n"
