#!/bin/bash
#
# .github/citools/go/go-lint-misspell
#

# go install github.com/client9/misspell/cmd/misspell@latest

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -a args
args=("${@}")
if [[ ${#args[@]} -eq 0 ]]; then
	args=()
fi

main() {
	printf "\nRunning Go misspell\n\n"

	show_tool_versions_go

	print_ruler

	run_command misspell "${args[@]}" .

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
