#!/bin/bash
#
# .github/citools/go/go-lint-gocritic
#

# go install -v github.com/go-critic/go-critic/cmd/gocritic@latest

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -a args
args=("${@}")
if [[ ${#args[@]} -eq 0 ]]; then
	args=(check -enableAll)
fi

main() {
	printf "\nRunning Go gocritic\n\n"

	show_tool_versions_go

	print_ruler

	run_command go clean ./...

	print_ruler

	run_command gocritic "${args[@]}" ./...

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
