#!/bin/bash
#
# .github/citools/go/go-lint-go_vet
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -a args
args=("${@}")
if [[ ${#args[@]} -eq 0 ]]; then
	args=()
fi

main() {
	printf "\nRunning Go Vet\n\n"

	show_tool_versions_go_short

	print_ruler

	run_command go clean ./...

	print_ruler

	run_command go vet "${args[@]}" ./...

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
