#!/bin/bash
#
# .github/citools/go/go-setup-config
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "Setup Go Environment\n\n"

	print_ruler

	printf "Adding paths to GITHUB_PATH...\n"
	printf "%s\n" "/usr/local/go/bin" | tee -a "${GITHUB_PATH}"

	print_ruler

	tree /usr/local/go/bin

	print_ruler

	tail -n 1000 -v "${GITHUB_PATH}"

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
