---
#
# .github/workflows/bash.yml
#
# https://github.com/reviewdog/action-shellcheck
#
name: Bash Checks
on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          path: "."
          exclude: |
            "./.git/*"
            "./tcl/*"
            bats-extra.bash
          check_all_files_with_shebangs: "false"
          level: error
