#
# https://github.com/get-woke/woke-action
#

name: Woke (push)

on:
  push:
    branches:
      - main
      - develop

jobs:
  woke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      # See https://github.com/marketplace/actions/get-all-changed-files
      - name: get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: woke
        id: woke
        uses: get-woke/woke-action@v0
        with:
          # Enable this to fail the check when violations are found
          fail-on-error: false

          # for more options
          woke-args: ${{ steps.files.outputs.added_modified }}
