#!/bin/bash
#
# .github/citools/rust/rust-lint-audit
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	deps=$(cargo tree | wc -l)
	((deps--))
	if [[ ${deps} -eq 0 ]]; then
		printf "No deps found, skipping cargo audit.\n"

		return "${retval}"
	fi

	printf "Running Rust Cargo Audit\n\n"

	show_tool_versions_rust

	print_ruler

	run_command cargo clean

	print_ruler

	run_command cargo tree

	print_ruler

	# https://docs.rs/cargo-audit/latest/cargo_audit/

	run_command cargo audit "${@}"

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
