#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

declare -i retval=0

main() {
	printf "\nRunning Rust Cargo Check\n\n"

	printf "Running "
	rustc --version

	print_ruler

	echo Running: cargo clean
	time cargo clean

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-check.html

	echo Running: cargo check "${@}"
	printf "\n"
	time cargo check "${@}" || ((retval++))

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
