#!/bin/bash
#
# .github/citools/rust/rust-lint-check
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Rust Cargo Check\n\n"

	show_tool_versions_rust

	print_ruler

	run_command cargo clean

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-check.html

	run_command cargo check "${@}"

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
