#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

declare -i retval=0

main() {
	printf "\nRunning Rust Cargo Clippy\n\n"

	printf "Running "
	rustc --version

	print_ruler

	echo Running: cargo clean
	time cargo clean

	print_ruler

	# https://github.com/rust-lang/rust-clippy

	echo Running: cargo clippy "${@}"
	printf "\n"
	time cargo clippy "${@}" || ((retval++))

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
