#!/bin/bash
#
# .github/citools/rust/rust-setup-config
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "Setup Rust Environment\n\n"

	print_ruler

	source ../../.github/citools/common/gh-setup-env || exit

	tree /usr/local/cargo/bin

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
