#!/bin/bash
#
# .github/citools/rust/rust-test-with-llvm-coverage
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Rust Tests With LLVM Coverage\n\n"

	show_tool_versions_rust_short

	print_ruler

	run_command cargo clean

	print_ruler

	run_command cargo llvm-cov clean

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-test.html

	run_command cargo test --all-features --doc

	print_ruler

	# https://doc.rust-lang.org/rustc/instrument-coverage.html
	# https://github.com/taiki-e/cargo-llvm-cov

	# --no-clean let's us generate real reports later on
	run_command cargo llvm-cov --no-clean --all-features

	print_ruler

	run_command cargo llvm-cov report --lcov --output-path report.lcov

	# show missing coverage with source - seems to only work for bin projects
	run_command cargo llvm-cov --no-clean --all-features --show-missing-lines >coverage-missing-lines.txt

	print_ruler

	# show missing coverage with source - seems to only work for bin projects
	run_command cargo llvm-cov --no-clean --all-features --text --output-path=coverage-annotations.txt

	print_ruler

	run_command cargo llvm-cov clean

	print_ruler

	run_command lcov --list report.lcov
	printf "\n"
	run_command lcov --summary report.lcov

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
