#!/bin/bash
#
# .github/citools/rust/rust-lint-clippy
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Rust Cargo Clippy\n\n"

	show_tool_versions_rust_short

	print_ruler

	run_command cargo clean

	print_ruler

	# https://github.com/rust-lang/rust-clippy

	run_command cargo clippy "${@}"

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
