#!/bin/bash
#
# .github/citools/rust/rust-test-with-tarpaulin
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

main() {
	printf "\nRunning Rust Tests With Tarpaulin\n\n"

	show_tool_versions_rust

	print_ruler

	run_command cargo clean

	print_ruler

	# https://doc.rust-lang.org/cargo/commands/cargo-test.html

	run_command cargo test

	print_ruler

	# https://github.com/xd009642/tarpaulin

	# don't use --verbose, it exposes environment variables
	# echo Running: cargo tarpaulin --release --timeout=300 --bins --verbose
	# time cargo tarpaulin --release --timeout=300 --bins --verbose

	run_command cargo tarpaulin --release --timeout=300

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
