#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

printf "\nRunning Rust Cargo Audit"

echo Running: cargo clean
time cargo clean

print_ruler

# https://docs.rs/cargo-audit/latest/cargo_audit/

echo Running: cargo audit "${@}"
time cargo audit "${@}"

print_ruler
