#!/bin/bash

print_ruler() {
	printf "\n"
	printf "=%.0s" {1..79}
	printf "\n"
	printf "\n"
} # print_ruler()

main() {
	printf "Running automated test file(s):\n\n"

	print_ruler

	../../.github/citools/awk/awk-lint

	print_ruler

	../../.github/citools/awk/awk-bats

	print_ruler

	# git clone http://git.savannah.gnu.org/r/gawk.git
	# cd gawk
	# git checkout $(awk --version | awk '/^GNU Awk/ { print $3 }' | tr -d ',')
	# cd ..
	# git clone https://github.com/soimort/awkunit
	# cd awkunit
	# AWKSRCPATH=../gawk make
	# cp -v awkunit.so ~/.local/gawk/lib/awkunit.so

	# awkunit.so file needs to be in the lib directory
	# awkunit.awk file needs to be in the current directory

	../../.github/citools/awk/awk-test

	print_ruler

	# go install github.com/client9/misspell/cmd/misspell@latest

	echo Running: misspell .
	time misspell .

	print_ruler
} # main()

time main "$@" |& tee ./run-tests-awk.txt
